### ISSUE TITLE
Add instructions on how to compile the compiler from its source code

### ISSUE THREAD

**Issue by Natim** [elm/compiler#1894]
This was really useful, I wish it was added to the README of this repository.

![image](https://user-images.githubusercontent.com/229453/52573700-fa026880-2e1a-11e9-92b9-254c663ef494.png)

**Comment by fkellner** [comment]
with the current commit, `stack init` does not work. Thankfully, eh on the elm slack provided my with a custom stack.yaml that works:
```yaml
resolver: lts-13.27
projects:
   - '.'
extra-deps:
   - containers-0.5.11.0@sha256:28ad7337057442f75bc689315ab4ec7bdf5e6b2c39668f306672cecd82c02798
   - http-client-0.6.4@sha256:a74b417345857d4250bdb6d4ac7fd4a89fd2ad8efab3164c1a2b843398d5c13a
   - language-glsl-0.3.0@sha256:85c1e7bf2cf5d6e604b7a2899c27e2935033425944db200798e57849e64d4c81
   - network-2.6.3.6@sha256:1ca79d81af02d7acd6032d5e6c9bde4618a8fdcfbe19bd42b49d420183975df0
   - time-1.9.3@sha256:8f1b5448722a12a952248b356c9eb366e351226543d9086a2da71270522d5f45
   - binary-0.8.7.0@sha256:ae3e6cca723ac55c54bbb3fa771bcf18142bc727afd57818e66d6ee6c8044f12,7705
   - directory-1.3.4.0@sha256:500019f04494324d1df16cf83eefeb3f809b2b20b32a32ccd755ee0439c18bfd,2829
   - process-1.6.5.1@sha256:77a9afeb676357f67fe5cf1ad79aca0745fb6f7fb96b786d510af08f622643f6,2468
   - unix-2.7.2.2@sha256:e69269a17b9fa26cb77f3f55e86c39d0a4940ccfa0c4bc20826919d2572076ad,3496
```
