### ISSUE TITLE
Document Building From Source

### ISSUE THREAD

**Issue by fkellner** [elm/compiler#1948]
*Please document how to build elm from source*

Judging by the complexity of the old BuildFromSource.hs provided for 0.18 and older, how to build from source is not always totally obvious.

I had to ask the elm slack, and it seems like I'm not the only one having issues
(see e.g. https://github.com/elm/compiler/issues/1892).

In the end, a custom `stack.yaml` and `stack.build` did it for me (Ubuntu 16.04, x86-64)
```yaml
resolver: lts-13.27
projects:
   - '.'
extra-deps:
   - containers-0.5.11.0@sha256:28ad7337057442f75bc689315ab4ec7bdf5e6b2c39668f306672cecd82c02798
   - http-client-0.6.4@sha256:a74b417345857d4250bdb6d4ac7fd4a89fd2ad8efab3164c1a2b843398d5c13a
   - language-glsl-0.3.0@sha256:85c1e7bf2cf5d6e604b7a2899c27e2935033425944db200798e57849e64d4c81
   - network-2.6.3.6@sha256:1ca79d81af02d7acd6032d5e6c9bde4618a8fdcfbe19bd42b49d420183975df0
   - time-1.9.3@sha256:8f1b5448722a12a952248b356c9eb366e351226543d9086a2da71270522d5f45
   - binary-0.8.7.0@sha256:ae3e6cca723ac55c54bbb3fa771bcf18142bc727afd57818e66d6ee6c8044f12,7705
   - directory-1.3.4.0@sha256:500019f04494324d1df16cf83eefeb3f809b2b20b32a32ccd755ee0439c18bfd,2829
   - process-1.6.5.1@sha256:77a9afeb676357f67fe5cf1ad79aca0745fb6f7fb96b786d510af08f622643f6,2468
   - unix-2.7.2.2@sha256:e69269a17b9fa26cb77f3f55e86c39d0a4940ccfa0c4bc20826919d2572076ad,3496
```
(thanks to pd-andy and eh from the slack beginners channel!)

Also, there is a link loop:
 If I follow the link under "Install" in the README.md, I get to the instructions from the documentation. If I follow the link to the npm package from there and go to troubleshooting (since my platform is not supported), when I follow "build from source" I get to the elm-platform repo which shows a link that it has moved here...
