### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by aminnairi** [elm/compiler#2088]
**Quick Summary:** Elm does not work well with Docker Compose.

## SSCCE

1. Create a new test directory

```console
$ mkdir test
```

2. Change the current directory

```console
$ cd test
```

3. Create a new Docker Compose configuration

```console
$ touch docker-compose.yaml
$ vim docker-compose.yaml
```

```yaml
version: "3"

services:
    npm:
        image: node
        user: node
        working_dir: /home/node
        entrypoint: npm
        volumes:
            - .:/home/node

    node:
        image: node
        user: node
        working_dir: /home/node
        entrypoint: node
        volumes:
            - .:/home/node
```

4. Initialise a new NPM project

```console
$ docker-compose run --rm npm init --yes
```

5. Install the Elm binary

```console
$ docker-compose run --rm npm install --save-dev elm
```

6. Initialize a new Elm project

```console
$ docker-compose run --rm node ./node_modules/.bin/elm init
```

7. See the following error

![image](https://user-images.githubusercontent.com/18418459/79610339-a5324000-80f8-11ea-9e94-b31da054647b.png)

- **Elm:** elm@0.19.1-3
- **Operating System:** `Linux archlinux 5.4.28-1-lts #1 SMP Wed, 25 Mar 2020 13:04:22 +0000 x86_64 GNU/Linux`

**Comment by Razzeee** [comment]
Did you try not installing via npm but installing elm directly?

See: https://github.com/elm/compiler/blob/master/installers/linux/README.md

**Comment by lydell** [comment]
./node_modules/.bin/elm is not a JS file, it’s a binary, so you can’t run it with `node`. Did you mean something like this?

```
docker-compose run --rm ./node_modules/.bin/elm init
```

**Comment by aminnairi** [comment]
@Razzeee Thanks for your answer. I tried installing it directly from the binary and it works well indeed.

@lydell Thanks for your answer. Yes indeed it works when I don't prefix it with `node`. I didn't realize it was a plain binary. So I'll close this issue. I'll leave this updated version of the Docker Compose configuration for the record in case some newbie like me ever encounter this problem.

```yaml
version: "3"

services:
    npm:
        image: node
        user: node
        working_dir: /home/node
        entrypoint: npm
        volumes:
            - .:/home/node

    node:
        image: node
        user: node
        working_dir: /home/node
        entrypoint: node
        volumes:
            - .:/home/node


    sh:
        image: node
        user: node
        working_dir: /home/node
        volumes:
            - .:/home/node
```

```console
$ docker-compose run --rm sh ./node_modules/.bin/elm init
```
